### ISSUE TITLE
Unable to setup email

### ISSUE THREAD

**Issue by Packitin** [nebhead/garage-zero-v2#3]
Good day, after my first remote got broken and the second on (key chain) got lost, I went looking for a remote Chamberlain Smart MyQ. Some people said it may or may not work on some models, I found your project and said this is what I need.  Everything works but I can't get the email to work, I reinstalled the program a second time so this is not the issue.  Am I missing something? 
This is the perfect solution for my good old faithful.

Thanking you in advance.

**Comment by nebhead** [comment]
Yep, another user pointed this out to me recently. For some reason the functionality broke, perhaps with a software update.  I'll work on debugging next week.  Will update when I get it resolved.

**Comment by Packitin** [comment]
Thank-you for your efforts, great project.

**Comment by nebhead** [comment]
OK... I think I have a fix for the issue.  I am testing and will update you as soon as I confirm it is working.

**Comment by nebhead** [comment]
All fixed up, I think.  Would love if you could test and report back.  

https://github.com/nebhead/garage-zero-v2/releases/tag/v2.0.7

This version does require a fresh install because of some of the changes I have made to the installation script and what versions of python modules get installed.

**Comment by Packitin** [comment]
OK, which version of raspbian did you use?

**Comment by nebhead** [comment]
Raspberry Pi OS Lite (Bookworm or Bullseye)

**Comment by Packitin** [comment]
OK, I'll start installing and update when I done. Thank-you for a speedy resolution.

**Comment by Packitin** [comment]
I tried both Gmail and Yahoo and I'm not receiving any notification. I did notice in the password window it remains blank after I enter my password and save. Should I see some asterisk ?
![2024-06-25 08_49_54-Window](https://github.com/nebhead/garage-zero-v2/assets/173550474/e53ffc5d-9d7e-4aa2-b835-8e0b9a0c82c1)

**Comment by Packitin** [comment]
I also tried Pushover, no luck.

**Comment by nebhead** [comment]
OK, let me look into it and get back to you.  

I'm not quite familiar with how yahoo's e-mail server works, but I think you don't need the @yahoo.com on the username.  Just the first part.  Also, the password would be obscured for security reasons... but I will double check that field on my end.

**Comment by nebhead** [comment]
Oh... you know, you do have to enable the notifications that you want in the door settings.  Example: 

![image](https://github.com/nebhead/garage-zero-v2/assets/19876886/8299fc82-0183-486f-a785-3f013f33a4e8)

Select the door you want to edit, then click the pencil next to it. 

Then scroll down and select the event you want to be notified of - click the pencil next to that. 

![image](https://github.com/nebhead/garage-zero-v2/assets/19876886/3913b97b-08e9-417c-9aa4-3c603963fb1a)

Then select the notification services you want to use for this event.  (ctrl + click allows you to select multiple)

![image](https://github.com/nebhead/garage-zero-v2/assets/19876886/d91fe0f7-2dda-45ea-8a39-fa6b7e6206c2)

Then click save on this page, and save on the next page.  This should enable your notifications.  You can do this for any of the events that you want to be notified with.  

Also... keep in mind that some mail servers require an application specific password for the e-mail to work properly.  So keep that in mind.

**Comment by Packitin** [comment]
**Pushover is working**, I had email selected that's why it didn't work.  Email still not working, I tried;
Server - smtp.mail.yahoo.com
both Port - 465 or 587 and checked off tls.
Gmail requires application specific password and that didn't work, that's why I tried yahoo mail. I don't see an SSL setting in the Notify Services is this automatically set?

**Comment by Packitin** [comment]
It looks like Yahoo has disabled App Password for less secure apps.  I think for now the push services is a viable solution.  Thank-you for finding a solution.

**Comment by nebhead** [comment]
Prototype looks great!

I have gmail working, but I'll need to wait until I get home to give you
the details from my setup. If I can remember correctly, it would look
something like this:

To E-mail:  ***@***.***
From E-mail: ***@***.***
Username: your_from_email *(without the @gmail.com <http://gmail.com>)*
Password: app_specific_password_here
smtp Server: smtp.gmail.com
port: 587
tls: checked

**Comment by Packitin** [comment]
Thank-you for your guidance, Email is now working. app_specific_password_here is not clearly indicated on there site.

**Comment by nebhead** [comment]
Wonderful!  I'll go ahead and close this out and hope you enjoy!
